### ISSUE TITLE
2 Factor Support?

### ISSUE THREAD

**Issue by cwawak** [gentoo-root/certbot-dns-henet#5]
I think it is probably impossible to hack in 2 Factor Support ... but it would still be nice!

**Comment by gentoo-root** [comment]
Wow, I didn't know that he.net supports 2FA.

Supporting 2FA will be tricky, as normally certbot renewals are unattended, and 2FA implies user interaction. Usually, web services provide API keys or application passwords for such applications. That's probably not the case with dns.he.net, is it?

I don't have plans to implement 2FA support, because the main purpose of this project is my personal use, and my use case is running `certbot renew` by a systemd timer, which means I won't be able to enter 2FA passwords anyway. However, I understand it may be useful for other people, so if you manage to hack on this feature, patches are welcome. Assuming that certbot allows some user interaction (in order to be able to enter the 2FA password), that might work for someone.

**Comment by cwawak** [comment]
Thank you!
